version: '3'

services:
  web:
    build: .
    command: >
      bash -c "alembic upgrade head && nohup python -m uvicorn app.main:app --port 8000 --host 0.0.0.0"
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db

  db:
    container_name: pg_db
    image: postgres:14-alpine
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
