"""add username to post_comments table

Revision ID: 155b7248e15c
Revises: fe2bed694c38
Create Date: 2023-05-08 10:45:25.629159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '155b7248e15c'
down_revision = 'fe2bed694c38'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_comments', sa.Column('username', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_comments', 'username')
    # ### end Alembic commands ###
