"""add file column into post table

Revision ID: 17cad35242f0
Revises: 36010e7c4737
Create Date: 2023-05-09 10:27:25.327656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17cad35242f0'
down_revision = '36010e7c4737'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('file', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'file')
    # ### end Alembic commands ###
