"""add date column

Revision ID: 36010e7c4737
Revises: 9058c50a8336
Create Date: 2023-05-08 13:18:50.679532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36010e7c4737'
down_revision = '9058c50a8336'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'time')
    # ### end Alembic commands ###
