"""delete author_id

Revision ID: 5d69d45067cf
Revises: c5be75b8e1c2
Create Date: 2023-05-05 10:46:57.739079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d69d45067cf'
down_revision = 'c5be75b8e1c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'author_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('author_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
