"""add author_id

Revision ID: 7254aaa18417
Revises: 5d69d45067cf
Create Date: 2023-05-05 10:47:31.481444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7254aaa18417'
down_revision = '5d69d45067cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('author_id', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'author_id')
    # ### end Alembic commands ###
